# Site settings
title: LOVE & PEACE
email: lsanotes@live.com
theme: jekyll-theme-minimal
description: > # this means to ignore newlines until "baseurl:"
  May mercy, peace, and love be multiplied to you.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lsanotes.github.io" # the base hostname & protocol for your site
twitter_username: lsanotes
github_username:  lsanotes

# Build settings
markdown: kramdown
